### ISSUE TITLE
Android 15 not supported (new devices with page size 16kb)

### ISSUE THREAD

**Issue by hooliapps** [brodycj/cordova-sqlite-ext-deps#4]
Android 15 not supported (new devices with page size 16kb)

I created a test change to correct the problem:

https://github.com/brodycj/cordova-sqlite-ext-deps/pull/3

**Comment by ancipov** [comment]
> Android 15 not supported (new devices with page size 16kb)
> 
> I created a test change to correct the problem:
> 
> [#3](https://github.com/brody4hire/cordova-sqlite-ext-deps/pull/3)

I build apk file with your fix but got the following error when run the app

java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlc-ndk-native-driver.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
